# Generated by Django 3.1.4 on 2020-12-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='details',
            new_name='detail',
        ),
        migrations.RenameModel(
            old_name='movies',
            new_name='movie',
        ),
    ]
